swagger: "2.0"
info:
  title: "Hello World"
  description: "API para retornar um Hello World"
  version: 1.0.0
host: "localhost:8000"
basePath: /api/
schemes:
  - http
paths:
  /v1/api/videos:
    get:
      summary: "API Get "
      description: "Descrição opcional"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/response"
    post:
        summary: "API Post "
        description: "Descrição opcional"
        responses:
          "200":
            description: "successful operation"
            schema:
              $ref: "#/definitions/response"
  /v1/api/videos/{id}:
    get:
      summary: "API Get "
      description: "Descrição opcional"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/response"
definitions:
  response:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
